### PR TITLE
Suggestions for littlebot

### PR DESCRIPTION
**Pull request by fjp**
Hi @NestorDP I looked through the gazebo-, description- and control-packages of littlebot and have just the following suggestions in this PR:
- I added a macro for the sonars in littlebot.xacro to make it shorter
- The `state_publisher` is deprecated in newer ROS distributions, so I updated it to `robot_state_publisher`

Other points I haven't changed are the following:
- I think it's common to use a [`base_footprint`](https://www.ros.org/reps/rep-0120.html#base-footprint) link according to REP-120, so this could be added to littlebot.
- In your package.xml you are using format version 1 instead of version 2. It is [recommended to use v2](http://docs.ros.org/kinetic/api/catkin/html/howto/format2/index.html).
- Instead of having a transmission tag in your urdf for the caster wheel joints, you could use the `joint_state_publisher`'s [`extra_joints` configuration](http://docs.ros.org/noetic/api/joint_state_controller/html/c++/classjoint__state__controller_1_1JointStateController.html#details).

And finally I get the following warnings but I don't know how to solve them and maybe its just my fault:

```
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link at time 2317.102000 according to authority /ekf_localization
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
```

and when running rviz: 

```
[ WARN] [1601424585.519193911, 2487.003000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link at time 2486.982000 according to authority unknown_publisher
[ WARN] [1601424585.563635658, 2487.042000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link at time 2487.022000 according to authority unknown_publisher
[ WARN] [1601424585.610154629, 2487.082000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_link at time 2487.062000 according to authority unknown_publisher
```

Otherwise the the packages I've reviewed look good, great work so far :clap:  Especially on the sonar rig :+1: 

Unfortunately I haven't had enough time to review the navigation or ekf packages and I haven't really used those too. So maybe in the future I can give you my opinions on these :wink:

### CODE REVIEW

**Review by NestorDP — COMMENTED** [review]
Hi @fjp I already made these changes to the feature/robot_model branch, this branch is more current than the master branch. Try running the feature/robot_model branch you will see some updates on the meshs

**Review by NestorDP — APPROVED** [review]
It was very good

**Comment by fjp** [comment]
Thanks, I'll checkout the feature/robot_model branch.

**Comment by NestorDP** [comment]
Thanks for the suggestions, I have little time to work on littlebot now, but as soon as I have time I will calmly review your suggestions and give you feedback.

**Pull request merged**
